# -*- coding: utf-8 -*-
"""Assignemnt2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TT3LVSQjNvGgV1_za0feuBNYUyoLzxA
"""

pip install geemap

pip install geemap[raster]

pip install geemap[lidar]

pip install geemap[sql]

pip install geemap[streamlit]

import geemap.geemap as map

import ee

ee.Authenticate()

ee.Initialize(project= 'ee-shirwadkarsejal809')

import geemap.geemap as geemap

m = geemap.Map()
m

m.add_basemap('HYBRID')

studyarea=ee.FeatureCollection('projects/ee-shirwadkarsejal809/assets/AIZWAL')

Aizawal = ee.FeatureCollection('projects/ee-shirwadkarsejal809/assets/AIZWAL')
m.addLayer(Aizawal, {}, 'Aizawal')
m

sentinel_data_2016=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2016-06-01', '2016-12-31')
sentinel_data_2024=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2024-06-01', '2024-12-31')

sentinel_2016_tcc=sentinel_data_2016.select('B4','B3','B2').mean().clip(Aizawal)

Aizawal_Fcc = ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2016-06-01', '2016-12-31')
Aizawal_Fcc = Aizawal_Fcc.mean().clip(Aizawal)
m.addLayer(Aizawal_Fcc, {}, 'FCC')
m

Aizawal_Fcc1 = ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2024-06-01', '2024-12-31')
Aizawal_Fcc1 = Aizawal_Fcc1.mean().clip(Aizawal)
m.addLayer(Aizawal_Fcc1, {}, 'FCC1')
m

Aizawal_TCC = ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2024-06-04', '2024-12-25')
Aizawal_TCC = Aizawal_TCC.mean().clip(Aizawal)
m.addLayer(Aizawal_TCC, {}, 'TCC')
m

Aizawal_TCC = ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2016-06-04', '2016-12-25')
Aizawal_TCC = Aizawal_TCC.mean().clip(Aizawal)
m.addLayer(Aizawal_TCC, {}, 'TCC1')
m

Aizawal_Fcc = ee.ImageCollection("LANDSAT/LC09/C02/T1").filterDate('2024-08-01', '2024-12-25')
Aizawal_Fcc = Aizawal_Fcc.mean().clip(Aizawal)
m.addLayer(Aizawal_Fcc, {}, 'Landsat_fcc')
m

Aizawal_Fcc = ee.ImageCollection("LANDSAT/LE07/C02/T1").filterDate('2000-08-01', '2000-12-25')
Aizawal_Fcc = Aizawal_Fcc.mean().clip(Aizawal)
m.addLayer(Aizawal_Fcc, {}, 'Landsat_fcc1')
m

Aizawal_Tcc = ee.ImageCollection("LANDSAT/LC09/C02/T1").filterDate('2024-08-01', '2024-12-25')
Aizawal_Tcc = Aizawal_Tcc.mean().clip(Aizawal)
m.addLayer(Aizawal_Tcc, {}, 'Landsat_Tcc')
m

Aizawal_Tcc = ee.ImageCollection("LANDSAT/LE07/C02/T1").filterDate('2000-08-01', '2000-12-25')
Aizawal_tcc = Aizawal_Tcc.mean().clip(Aizawal)
m.addLayer(Aizawal_Fcc, {}, 'Landsat_Tcc1')
m

vector_layer = ee.FeatureCollection("projects/ee-shirwadkarsejal809/assets/Waterways")

Map=geemap.Map()
m

Map.addLayer(vector_layer, {}, 'Waterways')

VectorLayer = ee.Image("Waterways").clip(Aizawal)
m.addLayer(vector_layer, {}, 'Aizawal_waterways')
m